### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by bubudrc** [v-braun/VBPiledView#2]
On your gif example, you show a text on each cell. How can I add that label?

Thanks.

Regards

**Comment by v-braun** [comment]
The first GIF use the component, the second example (which you mean) was my expiration for it.
But you can do it also.

The protocol function `piledView(viewForPiledView: VBPiledView, itemAtIndex index: Int) -> UIView` want a UIView from you:

``` swift
  func piledView(viewForPiledView: VBPiledView, itemAtIndex index: Int) -> UIView {
    return // a view at "index"
  }
```

Create a UIView, add a UIImage as subview with your image and add a UILabel on the UIView as subview with your text.

Do you need a sample code?
Can code it for you later.

[UPDATE]
I implemented your case with LayoutConstraints as an example.
Check the code and run the second example.

**Comment by bubudrc** [comment]
ok.. thanks @v-braun. If you can code the example and add to the readme will be awesome.

Thanks for your help.

**Comment by v-braun** [comment]
I implemented it!
Check it in the example project:
https://github.com/v-braun/VBPiledView/blob/master/Example/Example/ImgWithTextViewController.swift

**Comment by bubudrc** [comment]
wow man, that is awesome. Thanks for your framework, help and example 👍
