### ISSUE TITLE
Resize rows

### ISSUE THREAD

**Issue by gorbat-o** [v-braun/VBPiledView#3]
Hey,

How can i easily resize rows with your lib?
Maybe can you implement it ? ;)

If you do not have time, i can make a pull request when i've got some times for this.
later,

**Comment by v-braun** [comment]
Don't really understand what you want to do :)

Want you resize the Image in the "full" presentation?
The height of the full size image is limited by the height of your device and the number of the other (collapsed) images.

**Comment by gorbat-o** [comment]
Hey,
thanks for answer,
I'm talking about the size of row,
if we want to change the value, like minimum 80 to 40 or to 120 for example,

:)

**Comment by v-braun** [comment]
ok ... think understand your requirement now!
You can create a pull request if you have a great solution for that.
I'll check it in the next days too.

**Comment by v-braun** [comment]
2 discuss: it would be nice if the sizes can be set in percentage to make a responsive behavior possible.

Fixed sizes are bad for the different screen sizes.

**Comment by v-braun** [comment]
Implemented the requested feature.
Check documentation section [configuration](https://github.com/v-braun/VBPiledView#configuration) to see how you can use it.

**Comment by gorbat-o** [comment]
nice :)
Thanks !

**Comment by v-braun** [comment]
will do a pod update later

EDIT:
after you check it and approve the solution ;-)
