### ISSUE TITLE
Item selection

### ISSUE THREAD

**Issue by sebastienboulogne** [v-braun/VBPiledView#4]
Hey, very cool work but how do you retrieve an item index click ? I mean i want to perform a segue retrieving the index item and its label title ? Thx :)

**Comment by v-braun** [comment]
I didn't handle any user interactions within the View.
The instances you return with
`piledView(viewForPiledView: VBPiledView, itemAtIndex index: Int) -> UIView`
are stored within the view and get never removed.

For your case:
- Create your views
- Attach gesture recognizer to them (only once and **not** on every call of "viewForPiledView")
- Set the dataSource and show the PiledView

IMPORTANT:
This behavior means that **all** of the views get never removed!
You shouldn't use to many views within the PiledView (maybe not more than 100!???)

Hope this help you?

**Comment by wdcurry** [comment]
beautiful end result in this repo but the view retrieval count is staggering. One simple view with a few seconds of scrolling can result in thousands of calls, thousands!  That is just too much. Love the look though, and perhaps will revisit to fork and re-jig unless it gets optimized before i can.  Great inspiration though, thank you.

**Comment by v-braun** [comment]
@wdcurry thanks for your feedback!
Unfortunately, I'm busy with some projects and have not the time to work on that.
If you find the time it will be great! Thanks again
